/*Сотрудник с максимальной ЗП*/
SELECT NAME AS 'Имя', SALARY AS 'ЗП'
FROM t_EMPLOYEE 
WHERE SALARY = (SELECT MAX(SALARY) FROM t_EMPLOYEE);

/*Отдел, в котором работает сотрудник с самой высокой ЗП*/
SELECT t_DEPARTMENT.NAME AS 'Отдел'
FROM t_DEPARTMENT JOIN t_EMPLOYEE ON DEPARTMENT_ID = t_DEPARTMENT.ID
WHERE SALARY = (SELECT MAX(SALARY) FROM t_EMPLOYEE);

/*Отдел с максимальной суммой ЗП сотрудников */
SELECT t_DEPARTMENT.NAME AS 'Отдел', SUM(t_EMPLOYEE.SALARY) AS 'Сумма'
FROM t_DEPARTMENT JOIN t_EMPLOYEE ON t_DEPARTMENT.ID = DEPARTMENT_ID
GROUP BY t_DEPARTMENT.NAME
HAVING SUM(SALARY) = (SELECT MAX(S_SUM) AS MAX_SUM
FROM (SELECT SUM(t_EMPLOYEE.SALARY) AS S_SUM
FROM t_DEPARTMENT JOIN t_EMPLOYEE ON t_DEPARTMENT.ID = DEPARTMENT_ID
GROUP BY t_DEPARTMENT.NAME) MAX_QUERY);

/*Сотрудник, имя которого начинается на "Р" и заканчивается на "н"*/
SELECT NAME AS 'Имя', SALARY AS 'Зарплата' 
FROM t_EMPLOYEE
WHERE NAME LIKE 'Р%н';
