//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsFrequencyNew.FDService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/FreqService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FDService.IFreqService")]
    public interface IFreqService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreqService/GetData", ReplyAction="http://tempuri.org/IFreqService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreqService/GetData", ReplyAction="http://tempuri.org/IFreqService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreqService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IFreqService/GetDataUsingDataContractResponse")]
        WordsFrequencyNew.FDService.CompositeType GetDataUsingDataContract(WordsFrequencyNew.FDService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreqService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IFreqService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WordsFrequencyNew.FDService.CompositeType> GetDataUsingDataContractAsync(WordsFrequencyNew.FDService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreqService/GetFrequencyDict", ReplyAction="http://tempuri.org/IFreqService/GetFrequencyDictResponse")]
        System.Collections.Generic.KeyValuePair<string, int>[] GetFrequencyDict(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFreqService/GetFrequencyDict", ReplyAction="http://tempuri.org/IFreqService/GetFrequencyDictResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, int>[]> GetFrequencyDictAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFreqServiceChannel : WordsFrequencyNew.FDService.IFreqService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FreqServiceClient : System.ServiceModel.ClientBase<WordsFrequencyNew.FDService.IFreqService>, WordsFrequencyNew.FDService.IFreqService {
        
        public FreqServiceClient() {
        }
        
        public FreqServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FreqServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FreqServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FreqServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WordsFrequencyNew.FDService.CompositeType GetDataUsingDataContract(WordsFrequencyNew.FDService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WordsFrequencyNew.FDService.CompositeType> GetDataUsingDataContractAsync(WordsFrequencyNew.FDService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Collections.Generic.KeyValuePair<string, int>[] GetFrequencyDict(string text) {
            return base.Channel.GetFrequencyDict(text);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, int>[]> GetFrequencyDictAsync(string text) {
            return base.Channel.GetFrequencyDictAsync(text);
        }
    }
}
